#
# This file contains configuration flags to customize your site - used to force update
#

################################################################################
# main variables:
################################################################################

name: Pandalism
tagline: Felix DMR's Blog
description: Programming, Electronics, Autonomous Vehicles and other interests!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/Logo/Logo-Transparent.png

# Social Media icons
social-media:
  email_ciphered: you+need+js+for+this+to+work
  email_key: "20,14,28,71,26,10,95,7,68,4,7,74,5,27,31,78,52,14,12,31,66,12,11,70,5,65,17,4,109"
  # email: "mailto: "
  feed: feed.xml
  linkedin: felixdmr
  # instagram: felixdmr
  github: Pandalism


# Collections
collections:
  projects:
    output: false

# Used for Sitemap.xml and your RSS feed
url: https://felixdmr.com
baseurl: ""

# set permalinks to be /year/month/day/title
permalink: /:year/:month/:day/:title/


# Plugin options
emoji:
  src: "/assets/"

paginate: 4
paginate_path: "/blog/page:num/"


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass # ensure imports are from the correct dir
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji # Adds github emoji's
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
