#
# This file contains configuration flags to customize your site - used to force update
#

################################################################################
# main variables:
################################################################################

name: Pandalism
tagline: AKA Felix DMR
description: Programming, Electronics, Autonomous Vehicles and other interests!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/Logo/Logo-Transparent.png

# Social Media icons
social-media:
  email: contactfelix@felixdmr.com
  linkedin: felixdmr
  # instagram: felixdmr
  github: Pandalism



# Used for Sitemap.xml and your RSS feed
url: http://felixdmr.com
baseurl: ""

# set permalinks to be /catergories/year/month/day
permalink: pretty


# Plugin options
emoji:
  src: "/assets/"



# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass # ensure imports are from the correct dir
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji # Adds github emoji's

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
